branches:
  only:
  - v2.0
language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
matrix:
  allow_failures:
  - node_js: '0.11'
before_install:
- npm install -g grunt-cli
script:
- grunt
env:
  global:
    secure: d96Eo9anBBvr+Ucwb92yMp5ZCPi262adt6PsC8uLR+KggH2k8hU9ScAVY9OGttMecKN3dy/OevSbracBGl7C9SP/YTLfGSIO9gaPlPctqn/oF8y1xNzpr0E/KoR/uyLgUPtAWXWxUc4SK6SI3VliRFGDz6iRcVva6iWaDkUp9wY=
after_success:
  - curl -o travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          echo "All Succeded! PUBLISHING..."
          git clone "https://RReverser:$GH_TOKEN@github.com/jDataView/dist2.git" ../dist
          cp dist/browser/* ../dist/
          pushd ../dist
          git config user.email "me@rreverser.com"
          git config user.name "Ingvar Stepanyan"
          git add .
          git commit -m "Travis build $TRAVIS_BUILD_NUMBER"
          git push
          popd
        else
          echo "Some Failed"
        fi
      fi
deploy:
  provider: npm
  email: me@rreverser.com
  api_key:
    secure: EPycJqpKzGoptpxtiKZIE6o/4IDIONwDqyRg9mufeUtP+8d9oawKSaZzDRQ83JaBn5QLon+r/1Qhf7c3663GWhOuyjvfA0dH2VoF6dS9LIv7yOSLENzEVOZo89eBgR7xLbMynI/wzACGUo15NZObFPKJyYsxBauITvW2w4Gbd5I=
  on:
    tags: true
    repo: jDataView/jBinary
